FAILED_TEST_COUNT = 'failed_test_count'
PASSED_TEST_COUNT = 'passed_test_count'
SUSPICIOUS = 'suspicious'
COUNT = "count"
PASSING_COUNT = "passing_count"


BUG_ID = "BUG ID"
BUGGY_STM = "BUGGY STM"
FCFLA_RANK = "FCFLA:RANK"
FCFLA_EXAM = "FCFLA:EXAM"


FB_RANK = "Arrieta et al.:RANK"
FB_EXAM = "Arrieta et al.:EXAM"
FB_TC_RANK = "TC_Arrieta et al.:RANK"
FB_TC_EXAM = "TC_Arrieta et al.:EXAM"

FCFLA_TC_RANK = "FCFLA_WITH_SLICING:RANK"
FCFLA_TC_EXAM = "FCFLA_WITH_SLICING:EXAM"
TC_SPACE = "SLICING:SPACE"

FCFLA_SPACE = "FCFLA_ENABLE_BUGGY_PC_DETECTION:SPACE"
SBFL_EXAM = "SBFL:EXAM"
SBFL_RANK = "SBFL:RANK"
SBFL_TC_EXAM = "SBFL_TC:EXAM"
SBFL_TC_RANK = "SBFL_TC:RANK"
SPACE = "SPACE"
FCFLA_DISABLE_BPC_RANK = "FCFLA_DISABLE_BUGGY_PC_DETECTION:RANK"
FCFLA_DISABLE_BPC_EXAM = "FCFLA_DISABLE_BUGGY_PC_DETECTION:EXAM"

FCFLA_SEARCH_SPACE = "WITHOUT_ISOLATION_SPACE"

AGGREGATION_ARITHMETIC_MEAN = "AGGREGATION_ARITHMETIC_MEAN"
AGGREGATION_GEOMETRIC_MEAN = "AGGREGATION_GEOMETRIC_MEAN"
AGGREGATION_MIN = "AGGREGATION_MIN"
AGGREGATION_MAX = "AGGREGATION_MAX"
AGGREGATION_MEDIAN = "AGGREGATION_MEDIAN"
AGGREGATION_MODE = "AGGREGATION_MODE"
AGGREGATION_STDEV = "AGGREGATION_STDEV"
NORMALIZATION_DISABLE = "DISABLE_NORMALIZATION"
NORMALIZATION_ENABLE = "ENABLE_NORMALIZATION"

STATEMENT_ID = "stm_id"
VARIANTS_FAILED = "variants_failed"
VARIANTS_PASSED = "variants_passed"

SBFL_METRIC = "SBFL_METRIC"
NUM_BUGS = "NUM_OF_BUGS"
NUM_CASES = "NUM_OF_CASES"

NUM_OF_PASSING_VARIANTS = "num_of_passing_variants"
NUM_OF_FAILING_VARIANTS = "num_of_failing_variants"

HIT = "HIT@"
HIT_FCFLA = "FCFLA"
HIT_SBFL = "SBFL"
HIT_TC_SBFL = "S_SBFL"

#improvement comparison
FCFLA_VS_SBFL_IN_RANK = "FCFLA_VS_SBFL_IN_RANK"
FCFLA_VS_SBFL_IN_EXAM = "FCFLA_VS_SBFL_IN_EXAM"
FCFLA_DISABLE_BPC_VS_SBFL_IN_RANK = "FCFLA_DISABLE_BPC_VS_SBFL_IN_RANK"
FCFLA_DISABLE_BPC_VS_SBFL_IN_EXAM = "FCFLA_DISABLE_BPC_VS_SBFL_IN_EXAM"

FCFLA_WIN_RANK = "FCFLA_WIN:RANK"
FCFLA_WIN_EXAM = "FCFLA_WIN_EXAM"
FCFLA_DISABLE_BPC_WIN_RANK = "FCFLA_DISABLE_BPC_WIN_RANK"
FCFLA_DISABLE_BPC_WIN_EXAM = "FCFLA_DISABLE_BPC_WIN_EXAM"
SBFL_WIN_FCFLA_RANK = "SBFL_WIN_FCFLA_RANK"
SBFL_WIN_FCFLA_EXAM = "SBFL_WIN_FCFLA_EXAM"
SBFL_WIN_FCFLA_DISABLED_BPC_RANK = "SBFL_WIN_FCFLA_DISABLED_BPC_RANK"
SBFL_WIN_FCFLA_DISABLED_BPC_EXAM = "SBFL_WIN_FCFLA_DISABLED_BPC_EXAM"



#Variant
VARIANT_NUM_OF_PASSES = "VARIANT_NUM_OF_PASSES"
VARIANT_NUM_OF_FAILS = "VARIANT_NUM_OF_FAILS"


#search space
SS_FCFLA = "SS_FCFLA"
SS_SLICING = "SS_SLICING"
SS_ALL_STMS = "SS_ALL_STMS"
SS_STMS_IN_F_PRODUCTS = "SS_STMS_IN_F_PRODUCTS"


RANK = "RANK"
EXAM = "EXAM"